import type { CommandSpec } from '@/core/command'
import {
  CornerDownLeft,
  ArrowDown,
  ArrowUp,
  X as IconX,
  Search as IconSearch,
  Copy,
  FolderOpen,
  FileText,
  Info,
  Trash2,
  FolderOpen as FolderOpenIcon,
  Pin,
} from '@lucide/vue'

export const searchCommandSpecs: CommandSpec[] = [
  {
    id: 'search',
    title: '搜索',
    description: '搜索应用 / 文件 / 命令',
    category: 'search',
    keywords: ['find', 'fuzzy'],
    icon: IconSearch,
  },
  {
    id: 'search.cmd.execute-selected',
    title: '打开选中项',
    description: '执行当前高亮结果（Enter）',
    category: 'search',
    shortcut: 'Enter',
    keywords: ['open', 'run', 'enter'],
    icon: CornerDownLeft,
  },
  {
    id: 'search.cmd.next-item',
    title: '向下选择',
    description: '移动到下一项结果',
    category: 'search',
    shortcut: 'ArrowDown',
    keywords: ['down', 'next'],
    icon: ArrowDown,
  },
  {
    id: 'search.cmd.prev-item',
    title: '向上选择',
    description: '移动到上一项结果',
    category: 'search',
    shortcut: 'ArrowUp',
    keywords: ['up', 'prev'],
    icon: ArrowUp,
  },
  {
    id: 'search.cmd.close-window',
    title: '关闭搜索',
    description: '隐藏搜索窗口（Esc）',
    category: 'window',
    shortcut: 'Escape',
    keywords: ['close', 'hide', 'esc'],
    icon: IconX,
  },
  {
    id: 'search.cmd.toggle-window',
    title: '切换搜索窗口',
    description: '显示 / 隐藏搜索窗口（Alt+Space）',
    category: 'window',
    shortcut: 'Alt + Space',
    keywords: ['toggle'],
    icon: IconSearch,
  },
  {
    id: 'search.cmd.focus-input',
    title: '聚焦输入框',
    description: '把光标移到搜索输入框',
    category: 'search',
    keywords: ['focus'],
  },
  {
    id: 'search.cmd.clear-input',
    title: '清空查询',
    description: '清空当前搜索关键字',
    category: 'search',
    shortcut: 'Ctrl + K',
    keywords: ['clear'],
    icon: IconX,
  },
  {
    id: 'search.cmd.copy-selected-path',
    title: '复制完整路径',
    description: '复制当前结果的完整路径或名字到剪贴板',
    category: 'search',
    shortcut: 'Ctrl + C',
    keywords: ['copy', 'clipboard', 'path'],
    icon: Copy,
  },
  {
    id: 'search.cmd.reveal-selected',
    title: '打开文件所在路径',
    description: '在资源管理器中显示当前结果所在文件夹',
    category: 'search',
    shortcut: 'Ctrl + Enter',
    keywords: ['reveal', 'open folder', 'explorer'],
    icon: FolderOpen,
  },
  {
    id: 'search.cmd.copy-dir-path',
    title: '复制目录路径',
    description: '复制当前结果所在目录的完整路径',
    category: 'search',
    shortcut: 'Ctrl + Shift + C',
    keywords: ['copy', 'dir', 'folder', 'clipboard'],
    icon: FolderOpenIcon,
  },
  {
    id: 'search.cmd.copy-name',
    title: '复制文件名',
    description: '复制当前结果的文件名',
    category: 'search',
    keywords: ['copy', 'name', 'filename'],
    icon: FileText,
  },
  {
    id: 'search.cmd.show-properties',
    title: '显示属性',
    description: '显示当前文件或应用的属性对话框',
    category: 'search',
    shortcut: 'Alt + Enter',
    keywords: ['properties', '属性', 'info'],
    icon: Info,
  },
  {
    id: 'search.cmd.delete-selected',
    title: '删除到回收站',
    description: '将当前选中的文件删除到回收站',
    category: 'search',
    shortcut: 'Delete',
    keywords: ['delete', 'trash', 'remove', '删除'],
    icon: Trash2,
  },
  {
    id: 'search.cmd.toggle-pin',
    title: '固定 / 取消固定',
    description: '将当前项固定到首页或取消固定',
    category: 'search',
    keywords: ['pin', '固定', 'favorite'],
    icon: Pin,
  },
  {
    id: 'search.cmd.select-single',
    title: '单选',
    description: '单击选择单个项目，取消其他选中',
    category: 'search',
    keywords: ['single', 'click'],
  },
  {
    id: 'search.cmd.select-add',
    title: '加选 / 减选',
    description: 'Ctrl + 单击切换项目选中状态',
    category: 'search',
    shortcut: 'Ctrl + Click',
    keywords: ['add', 'toggle', 'ctrl'],
  },
  {
    id: 'search.cmd.select-range',
    title: '范围多选',
    description: 'Shift + 单击选中从上次选中到当前的所有项目',
    category: 'search',
    shortcut: 'Shift + Click',
    keywords: ['range', 'shift'],
  },
  {
    id: 'search.cmd.select-toggle-range',
    title: '范围反选',
    description: 'Ctrl + Shift + 单击反选范围内的项目',
    category: 'search',
    shortcut: 'Ctrl + Shift + Click',
    keywords: ['toggle', 'invert', 'ctrl+shift'],
  },
]
